### ISSUE TITLE
Unable to Launch on Win10 via Itch.io Desktop App

### ISSUE THREAD

**Issue by gryte** [hundredrabbits/Left#44]
## Expected Behavior

Within the **itch.io** *desktop* application, selecting *Launch* for the **Left** downloaded application should launch the application successfully.

## Current Behavior

The application never launches and no visible error messages are displayed.

If you *right-click* the *Launch* button for **Left**, then hover over *Advanced...*, and finally select *View logs...*, the following error message can be seen:

```bash
# snippet of much larger log file
# sensitive data purposely redacted
...
[2018-01-17 @ 17:56:53.848] [launch/native] out: User profile dir = C:\Users\itch-player-<redacted>
[2018-01-17 @ 17:56:53.850] [launch/native] out: Roaming AppData dir = C:\Users\itch-player-<redacted>\AppData\Roaming
[2018-01-17 @ 17:56:53.852] [launch/native] out: Local AppData dir = C:\Users\itch-player-<redacted>\AppData\Local
[2018-01-17 @ 17:56:53.852] [launch/native] out: Total environment length: 5640
[2018-01-17 @ 17:56:53.852] [launch/native] out: Environment buffer size: 7688
[2018-01-17 @ 17:56:53.853] [launch/native] out: Total environment length: 5640
[2018-01-17 @ 17:56:53.853] [launch/native] out: exe = 'C:\Users\adam\AppData\Roaming\itch\apps\Left\Left.exe'
[2018-01-17 @ 17:56:53.853] [launch/native] out: cwd = 'C:\Users\adam\AppData\Roaming\itch\apps\Left'
[2018-01-17 @ 17:56:53.963] [launch/native] out: 
[2018-01-17 @ 17:56:54.076] [launch/native] err: fs.js:1669
[2018-01-17 @ 17:56:54.077] [launch/native] err:       binding.lstat(baseLong);
[2018-01-17 @ 17:56:54.077] [launch/native] err:               ^
[2018-01-17 @ 17:56:54.077] [launch/native] err: 
[2018-01-17 @ 17:56:54.077] [launch/native] err: Error: EPERM: operation not permitted, lstat 'C:\Users\adam'
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at realpathSync (fs.js:1669:15)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at toRealPath (module.js:143:13)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at Function.Module._findPath (module.js:192:22)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at Function.Module._resolveFilename (module.js:483:25)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at Function.Module._load (module.js:437:25)
[2018-01-17 @ 17:56:54.077] [launch/native] err:     at Function.Module.runMain (module.js:605:10)
[2018-01-17 @ 17:56:54.078] [launch/native] err:     at startup (bootstrap_node.js:167:16)
[2018-01-17 @ 17:56:54.078] [launch/native] err:     at bootstrap_node.js:589:3
[2018-01-17 @ 17:56:55.226] [launch/icacls] [cleanup out] Successfully processed 1 files; Failed processing 0 files
...
```

## Possible Solution

Launching outside of the **itch.io** desktop app works just fine without issue.

Searching online and other github issues shows some interesting items that appear to be similar but nothing directly related to this issue. We seem to have some sort of permission problem relative to Electron *(I think...)*.
- aspnet/JavaScriptServices#1102
- electron/electron#9138
- electron/electron#11094

## Steps to Reproduce (for bugs)

1. Open **itch.io** desktop application
2. Search for **Left** and install it
3. Attempt to *Launch* **Left**
4. *Right-click* the *Launch* button to navigate to *Advanced...* and *View logs...*

## Context

I would like to leverage the **itch.io** desktop application in launching **Left** since it will handle updates for me.

## Your Environment

* Version used: **Left** is 'up to date' on **itch** `23.6.0`
  * per the *details* of the `left.exe` it's version `0.1.0`
* Environment name and version: n/a
* Server type and version: n/a
* Operating System and version: **Windows 10** `Build 16299`
* Link to your project: n/a

**Comment by neauoire** [comment]
Thanks! I'll have a look at that, although I don't have a Windows machine or know anyone close with one, would you be available to help me do some testing?

**Comment by gryte** [comment]
Absolutely!

**Comment by neauoire** [comment]
I have no idea how to fix this..
I'll have to do some digging.

**Comment by gryte** [comment]
No worries. I'll keep digging on my side and see if we can't meet in the middle with some sort of resolution.

**Comment by fasterthanlime** [comment]
This is definitely a symptom of https://github.com/itchio/itch/issues/1470.

Note that it only affects users who enabled the itch.io sandbox in their itch app preferences. (It's not enabled by default).

I'm also testing the itch app with other Electron apps ([fun example](https://github.com/fasterthanlime/sample-evil-app)) and haven't found an Electron-side workaround for now.

However, the next major release of the itch app should no longer have that issue - in the meantime, I'd recommend just disabling the sandbox when launching recent electron apps (that you trust).

**Comment by gryte** [comment]
Yup, I just disabled the sandbox and was able to launch Left without issue.

*In the itch.io desktop app*
1. navigate to **Preferences**
1. find **Security & privacy**
1. ensure the checkbox for **Enable itch.io sandbox** is unchecked


Thanks for the details!

**Comment by fasterthanlime** [comment]
![image](https://user-images.githubusercontent.com/7998310/45408877-e8e7dc80-b66d-11e8-9843-7d39ac88b676.png)

( itch v25 is out now at https://itch.io/app )

**Comment by neauoire** [comment]
Thanks @fasterthanlime <3
